apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-server
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      containers:
        - name: todo-server
          imagePullPolicy: Never # local image
          image: todo-server
          env:
            - name: PORT
              value: "5000"

# make sure to build and load the image before (see readme)
# apply changes: kubectl apply -f manifests/deployment.yaml